name = "devtrends-mysql-import"
main = "worker/catalog-import.mjs"
compatibility_date = "2026-09-14"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[hyperdrive]]
binding = "HYPERDRIVE_WRITE"
id = "5e20952cbb6d4407b42be43eb6e8f809"
