#!/usr/bin/env node
/**
 * Targeted media capture for Product Hunt posts that the raw 日报 references but
 * the official-featured subset never carried.
 *
 * Why this exists: the Product Hunt 日报 for 2026-01-01..2026-08 (and a few
 * September days) were generated by the retired mixed layer, whose per-day rows
 * are that day's top posts — not `featured: true` posts. Only the featured
 * subset projects `thumbnail`/`media`, so those rows have no product mark. This
 * script asks the API for exactly the referenced post IDs and stores their media
 * in a new `recordMedia` section on the same immutable day file:
 *
 *   { id, thumbnail, media, error }        // exactly as returned, no normalization
 *
 * `records` and `officialFeatured` are never touched, so day-level content and
 * their content hashes stay valid. The by-ID rows are additive provenance.
 *
 * Provenance rule: an ID is only requested for a day whose `records` (the full
 * sweep captured that day) already contains it. IDs that cannot be attributed
 * are skipped and reported, never guessed.
 *
 * Resumable: IDs already present in the day's `recordMedia` are skipped, so a
 * rate-limit restart only fetches what is still missing. Add
 * `--refresh-failures` to retry the IDs that previously errored.
 *
 * Requires PRODUCT_HUNT_TOKEN (shared rotation with capture_producthunt_raw.js).
 * Posts are looked up in aliased batches (`--batch-size`, default 20) because a
 * one-ID-per-request sweep only covers ~300 IDs inside a 15 minute quota window.
 *
 * Usage:
 *   node scripts/capture_producthunt_post_media.js --start 2026-01-01 --end 2026-09-10
 *   node scripts/capture_producthunt_post_media.js --start 2026-01-01 --end 2026-01-31 --dry-run
 *   node scripts/capture_producthunt_post_media.js --date 2026-02-02 --limit-ids 5
 */
const fs = require('fs');
const path = require('path');
const {
  requestGraphQL, waitForRateLimit, atomicWrite, digest,
} = require('./capture_producthunt_raw');

const SOURCE_ID = 'producthunt';
const ENDPOINT = 'https://api.producthunt.com/v2/api/graphql';
const MEDIA_FIELDS = ['id', 'thumbnail', 'media'];
const VAULT = path.resolve(__dirname, '..', '..', '..', '..');
const SOURCE_ROOT = path.join(VAULT, '知识', '大家都在做什么', 'source-raw', SOURCE_ID);
const RAW_ROOT = path.join(VAULT, '知识', '大家都在做什么', 'raw');

function value(argv, name) {
  const index = argv.indexOf(name);
  return index >= 0 ? argv[index + 1] : null;
}

function parseArgs(argv) {
  const date = value(argv, '--date');
  return {
    start: date || value(argv, '--start'),
    end: date || value(argv, '--end'),
    dryRun: argv.includes('--dry-run'),
    refreshFailures: argv.includes('--refresh-failures'),
    waitOnRateLimit: argv.includes('--wait-on-rate-limit'),
    limitIds: Number(value(argv, '--limit-ids')) || 0,
    batchSize: Number(value(argv, '--batch-size')) || 20,
  };
}

function eachDate(start, end) {
  const dates = [];
  const cursor = new Date(`${start}T00:00:00+08:00`);
  const last = new Date(`${end}T00:00:00+08:00`);
  while (cursor <= last) {
    dates.push(new Date(cursor).toLocaleDateString('sv-SE', { timeZone: 'Asia/Shanghai' }));
    cursor.setUTCDate(cursor.getUTCDate() + 1);
  }
  return dates;
}

// IDs the 日报 references that the featured projection does not cover. Days
// without a raw report contribute nothing: only consumed rows need media.
function neededIdsByDay(start, end, roots = {}) {
  const sourceRoot = roots.sourceRoot || SOURCE_ROOT;
  const rawRoot = roots.rawRoot || RAW_ROOT;
  const needed = new Map();
  const unattributable = [];
  let referenced = 0;
  for (const date of eachDate(start, end)) {
    const rawFile = path.join(rawRoot, `${date}.json`);
    const sourceFile = path.join(sourceRoot, `${date}.json`);
    if (!fs.existsSync(rawFile) || !fs.existsSync(sourceFile)) continue;
    const report = JSON.parse(fs.readFileSync(rawFile, 'utf8'));
    const rows = (report.results || [])
      .filter((source) => source.sourceId === SOURCE_ID)
      .flatMap((source) => source.items || []);
    if (!rows.length) continue;
    const document = JSON.parse(fs.readFileSync(sourceFile, 'utf8'));
    const featured = new Set((document.officialFeatured?.records || []).map((record) => String(record.id)));
    const allRecords = new Set((document.records || []).map((record) => String(record.id)));
    const existing = document.recordMedia?.records || [];
    const known = new Set(existing
      .filter((record) => record.error === null || !record.error)
      .map((record) => String(record.id)));
    const retryable = new Set(existing
      .filter((record) => record.error)
      .map((record) => String(record.id)));
    const ids = [];
    for (const row of rows) {
      const id = String(row.externalId || '');
      if (!id) continue;
      referenced += 1;
      if (featured.has(id) || known.has(id)) continue;
      if (retryable.has(id)) continue; // opt-in retry via --refresh-failures
      if (!allRecords.has(id)) {
        unattributable.push({ date, id });
        continue;
      }
      ids.push(id);
    }
    if (ids.length) needed.set(date, [...new Set(ids)].sort());
  }
  return { needed, unattributable, referenced };
}

function retryableFailuresByDay(start, end) {
  const retry = new Map();
  for (const date of eachDate(start, end)) {
    const sourceFile = path.join(SOURCE_ROOT, `${date}.json`);
    if (!fs.existsSync(sourceFile)) continue;
    const document = JSON.parse(fs.readFileSync(sourceFile, 'utf8'));
    const ids = (document.recordMedia?.records || [])
      .filter((record) => record.error && (document.records || []).some((row) => String(row.id) === String(record.id)))
      .map((record) => String(record.id));
    if (ids.length) retry.set(date, [...new Set(ids)].sort());
  }
  return retry;
}

// `thumbnail` and `media` are Media objects, so both need selections — asking for
// the bare field names makes PH reject the query with selectionMismatch.
const MEDIA_SELECTION = 'id\n      thumbnail { type url }\n      media { type url videoUrl }';

function postMediaQuery(id) {
  return `{
    post(id: ${JSON.stringify(id)}) {
      ${MEDIA_SELECTION}
    }
  }`;
}

// Aliased batch: several posts per request. Product Hunt's quota is consumed per
// request, and a one-ID-per-request sweep only lands ~300 IDs per 15 minute
// window, so batching is what keeps ~4000 lookups inside one or two windows.
function postMediaBatchQuery(ids) {
  const fields = ids
    .map((id, index) => `    p${index}: post(id: ${JSON.stringify(id)}) {\n      ${MEDIA_SELECTION}\n    }`)
    .join('\n');
  return `{\n${fields}\n  }`;
}

function mediaRecord(id) {
  return { id, thumbnail: null, media: null, error: null };
}

function postToRecord(post, fallbackId) {
  if (!post || !post.id) return { ...mediaRecord(fallbackId), error: 'post not found' };
  return {
    id: String(post.id),
    thumbnail: post.thumbnail ?? null,
    media: post.media ?? null,
    error: null,
  };
}

function rateLimitError(error, id) {
  const wrapped = new Error(`PH_API_RATE_LIMITED while fetching ${id}`);
  wrapped.code = 'PH_API_RATE_LIMITED';
  wrapped.retryAfterSeconds = error.retryAfterSeconds;
  return wrapped;
}

function fetchOne(id, options) {
  for (let attempt = 1; attempt <= 4; attempt += 1) {
    try {
      const { data } = requestGraphQL(postMediaQuery(id));
      return postToRecord(data.post, id);
    } catch (error) {
      if (error.code === 'PH_API_RATE_LIMITED' && options.waitOnRateLimit && attempt < 4) {
        waitForRateLimit(error, `post ${id}`);
        continue;
      }
      if (error.code === 'PH_API_RATE_LIMITED') throw rateLimitError(error, id);
      if (attempt === 4) return { ...mediaRecord(id), error: String(error.message || error).slice(0, 300) };
      // A GraphQL error is a query/schema problem, not a transient network blip:
      // record it once instead of burning retries on every remaining ID.
      if (/PH_API_ERROR/.test(String(error.message || error))) {
        return { ...mediaRecord(id), error: String(error.message || error).slice(0, 300) };
      }
      execSleep(attempt);
    }
  }
  return { ...mediaRecord(id), error: 'unreachable' };
}

function fetchBatch(ids, options) {
  if (ids.length === 1) return [fetchOne(ids[0], options)];
  try {
    const { data } = requestGraphQL(postMediaBatchQuery(ids));
    return ids.map((id, index) => postToRecord(data[`p${index}`], id));
  } catch (error) {
    if (error.code === 'PH_API_RATE_LIMITED') throw rateLimitError(error, ids[0]);
    // One rejected ID must not cost the whole batch: isolate it per ID.
    console.error(`[ph-media] batch of ${ids.length} failed (${String(error.message || error).slice(0, 120)}); retrying individually`);
    return ids.map((id) => fetchOne(id, options));
  }
}

function execSleep(seconds) {
  require('child_process').execFileSync('sleep', [String(seconds)]);
}

function writeDay(date, fetched) {
  const file = path.join(SOURCE_ROOT, `${date}.json`);
  const document = JSON.parse(fs.readFileSync(file, 'utf8'));
  const merged = new Map((document.recordMedia?.records || []).map((record) => [String(record.id), record]));
  for (const record of fetched) merged.set(String(record.id), record);
  const records = [...merged.values()].sort((a, b) => (String(a.id) < String(b.id) ? -1 : 1));
  document.recordMedia = {
    fetchedAt: new Date().toISOString(),
    endpoint: ENDPOINT,
    apiVersion: 'v2 GraphQL',
    sourceFields: MEDIA_FIELDS,
    requestedCount: records.length,
    itemCount: records.length,
    failureCount: records.filter((record) => record.error).length,
    complete: true,
    contentSha256: digest(records),
    records,
  };
  atomicWrite(file, `${JSON.stringify(document, null, 2)}\n`);
}

function main() {
  const options = parseArgs(process.argv.slice(2));
  if (!options.start || !options.end) throw new Error('--start/--end or --date is required');
  if (options.start > options.end) throw new Error('--start must not be after --end');

  const { needed, unattributable, referenced } = neededIdsByDay(options.start, options.end);
  if (options.refreshFailures) {
    for (const [date, ids] of retryableFailuresByDay(options.start, options.end)) {
      needed.set(date, [...new Set([...(needed.get(date) || []), ...ids])].sort());
    }
  }
  let planned = 0;
  for (const ids of needed.values()) planned += ids.length;
  const capped = options.limitIds ? Math.min(options.limitIds, planned) : planned;
  const summary = {
    start: options.start,
    end: options.end,
    referencedRows: referenced,
    daysNeedingMedia: needed.size,
    idsPlanned: planned,
    idsCapped: capped,
    unattributableIds: unattributable.length,
    dryRun: options.dryRun,
  };
  if (options.dryRun) {
    console.log(JSON.stringify({ ...summary, perDay: [...needed].slice(0, 5).map(([date, ids]) => ({ date, ids: ids.length })) }, null, 2));
    return;
  }

  let fetched = 0;
  let failed = 0;
  let writtenDays = 0;
  let remaining = capped;
  let rateLimited = false;
  const batchSize = Math.max(1, Math.min(50, options.batchSize || 20));
  const startedAt = Date.now();
  for (const date of [...needed.keys()].sort()) {
    if (remaining <= 0) break;
    const ids = needed.get(date).slice(0, remaining);
    const results = [];
    for (let start = 0; start < ids.length; start += batchSize) {
      const slice = ids.slice(start, start + batchSize);
      let records;
      try {
        records = fetchBatch(slice, options);
      } catch (error) {
        if (error.code === 'PH_API_RATE_LIMITED') {
          rateLimited = true;
          break;
        }
        throw error;
      }
      for (const record of records) {
        results.push(record);
        if (record.error) failed += 1;
        else fetched += 1;
      }
      remaining -= slice.length;
      console.error(`[ph-media] ${date}: ${Math.min(start + slice.length, ids.length)}/${ids.length} (${Math.round((Date.now() - startedAt) / 1000)}s)`);
    }
    if (results.length) {
      writeDay(date, results);
      writtenDays += 1;
      console.error(`[ph-media] ${date}: stored ${results.length} records`);
    }
    if (rateLimited) break;
  }

  console.log(JSON.stringify({
    ...summary,
    writtenDays,
    fetched,
    failed,
    rateLimited,
    unattributableSample: unattributable.slice(0, 5),
    elapsedSeconds: Math.round((Date.now() - startedAt) / 1000),
  }, null, 2));
  if (rateLimited) process.exitCode = 2;
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    console.error(error.stack || error.message);
    process.exit(1);
  }
}

module.exports = { neededIdsByDay, postMediaQuery, postMediaBatchQuery };
