#!/usr/bin/env node
/**
 * 详情页渲染版本（`worker/render-version.mjs`）的生成器。
 *
 * 动态产品页的边缘缓存键是 `CATALOG_VERSION + 渲染版本 + pathname`，而 `s-maxage` 是 24 小时。
 * 以前渲染版本是 `worker/index.js` 里的一个手改字符串：改了渲染逻辑忘了改它，线上最长一天
 * 还会读到旧渲染（2026-09-17 的投稿标签修复、09-18 的详情行重建都靠手工 `+1` 收尾）。
 *
 * 现在改成对**渲染链路的源码内容**取哈希，`npm run build` 时重新生成 —— 只要改了这些文件，
 * 缓存键必然换代，不需要有人记得手改。提交进仓库的那份只是让 diff 可读；Cloudflare Workers
 * Builds 每次都会先跑 `npm run build` 再 `wrangler deploy`，所以部署用的是重新生成的值。
 *
 * 注意 `RENDER_SOURCES` 里**不能**包含这个生成器或它写出的文件（会自指），所以版本常量已经
 * 从 `worker/index.js` 挪到了生成的模块里，`worker/index.js` 只负责 import。
 */
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const ROOT = path.resolve(__dirname, '..');
const OUTPUT = path.join('worker', 'render-version.mjs');
// 决定详情页 HTML 与页面数据的文件。新增渲染相关模块时要加进来，否则改它不会换代。
const RENDER_SOURCES = [
  'worker/index.js',
  'worker/project-page.mjs',
  'worker/mysql-db.mjs',
  'worker/catalog-api.mjs',
  'web/shared.js',
];

/** 渲染链路源码的内容哈希（16 位十六进制）。 */
function renderDigest(root = ROOT) {
  const hash = crypto.createHash('sha256');
  for (const relative of RENDER_SOURCES) {
    hash.update(`${relative}\0`);
    hash.update(fs.readFileSync(path.join(root, relative)));
    hash.update('\0');
  }
  return hash.digest('hex').slice(0, 16);
}

function renderVersion(root = ROOT) {
  return `r${renderDigest(root)}`;
}

function renderVersionModule(root = ROOT) {
  return `// Generated by scripts/render-version.js — 不要手改；npm run build 会重新生成。\n`
    + `export const PRODUCT_RENDERER_VERSION = '${renderVersion(root)}';\n`;
}

/** 重新生成 worker/render-version.mjs；内容没变时不写盘（避免无意义的重建 diff）。 */
function writeRenderVersion(root = ROOT) {
  const file = path.join(root, OUTPUT);
  const content = renderVersionModule(root);
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === content) return false;
  fs.writeFileSync(file, content);
  return true;
}

if (require.main === module) {
  const changed = writeRenderVersion();
  console.log(`${changed ? 'Wrote' : 'Unchanged'} ${OUTPUT}: ${renderVersion()}`);
}

module.exports = { RENDER_SOURCES, renderDigest, renderVersion, renderVersionModule, writeRenderVersion, OUTPUT };
